package:
  name: m4
  version: "1.4.17"

source:
  fn: m4-1.4.17.tar.gz
  url: http://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz
  md5: a5e9954b1dae036762f7b13673a2cf76

# requirements:
#   build:
    # - m4
