package:
  name: requests-kerberos
  version: "0.8.0"

source:
  fn: requests-kerberos-0.8.0.tar.gz
  url: https://pypi.python.org/packages/source/r/requests-kerberos/requests-kerberos-0.8.0.tar.gz
  md5: ff763a1cd59d95500802213f0eeba70b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - requests-kerberos = requests-kerberos:main
    #
    # Would create an entry point called requests-kerberos that calls requests-kerberos.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=1.1.0
    - kerberos-sspi >=0.2 [win]
    - pykerberos >=1.1.8,<2.0.0 [not win]

  run:
    - python
    - requests >=1.1.0
    - kerberos-sspi >=0.2 [win]
    - pykerberos >=1.1.8,<2.0.0 [not win]

test:
  # Python imports
  imports:
    - requests_kerberos

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
  #   - mock
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/requests/requests-kerberos
  license: UNKNOWN
  summary: 'A Kerberos authentication handler for python-requests'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
