package:
  name: kerberos-sspi
  version: "0.2"

source:
  fn: kerberos-sspi-0.2.tar.gz
  url: https://pypi.python.org/packages/source/k/kerberos-sspi/kerberos-sspi-0.2.tar.gz
  md5: 2244581f50ba2fb4c8987fb793fd7bd8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - kerberos-sspi = kerberos-sspi:main
    #
    # Would create an entry point called kerberos-sspi that calls kerberos-sspi.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pywin32

  run:
    - python
    - pywin32

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/may-day/kerberos-sspi
  license: Apache Software License
  summary: 'Kerberos high-level windows interface'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
