package:
  name: schematics
  version: "1.1.1"

source:
  fn: schematics-1.1.1.tar.gz
  url: https://pypi.python.org/packages/source/s/schematics/schematics-1.1.1.tar.gz
  md5: 2b9a10bac17c3879e27a67e1520de489
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - schematics = schematics:main
    #
    # Would create an entry point called schematics that calls schematics.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six >=1.7.3

  run:
    - python
    - six >=1.7.3

test:
  # Python imports
  imports:
    - schematics
    - schematics.contrib
    - schematics.types

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
  #   - coverage
  #   - mock >=1.0.1
  #   - pymongo >=2.7.1
  #   - pytest >=2.5.1
  #   - python-coveralls
  #   - python-dateutil >=2.2
  #   - sphinx >=1.1.3
  #   - tox >=1.9
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/schematics/schematics
  license: BSD
  summary: 'Structured Data for Humans'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
