package:
  name: flask-swagger
  version: "0.2.12"

source:
  fn: flask-swagger-0.2.12.tar.gz
  url: https://pypi.python.org/packages/96/ce/62fdad737c7e753866bb729f97f24361ef18b6da7640a66780adbc332893/flask-swagger-0.2.12.tar.gz
  md5: d28d069d3f8852465bbce3945ac38c3f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-swagger = flask-swagger:main
    #
    # Would create an entry point called flask-swagger that calls flask-swagger.main()

    - flaskswagger=build_swagger_spec:run

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask >=0.10
    - pyyaml >=3.0

  run:
    - python
    - setuptools
    - flask >=0.10
    - pyyaml >=3.0

test:
  # Python imports
  imports:
    - flask_swagger

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - flaskswagger --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/gangverk/flask-swagger
  license: MIT
  summary: 'Extract swagger specs from your flask project'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
